### ISSUE TITLE
feature suggestion - autoregister custom repositories

### ISSUE THREAD

**Issue by xpavp03** [contributte/doctrine-orm#112]
Could you please consider automatically registering custom repositories as DIC services?

My `services.neon` contains a lot of 
```
services:
	-
		create: @nettrine.orm.entityManagerDecorator::getRepository(App\Orm\Entity\Player)
		type: App\Orm\Repository\PlayerRepository
```

Nettrine extension could pick entities with `repositoryClass` set, and generate a factory for it in DIC.

I prefer to require specific repositories in my classes, rather than just EM, to be more clear about my dependencies and to minimize boilerplate code.

Thank you.

**Comment by f3l1x** [comment]
Hi, it's not a problem. I will do it.

**Comment by f3l1x** [comment]
Hi, I've discovered that's a little problem in multi-connection setup to autoregister repositories.

I would suggest to use your style or define custom repositories like that https://getrector.com/blog/how-to-instantly-decouple-symfony-doctrine-repository-inheritance-to-clean-composition.

You can combine custom repositories with search extension.

```neon
search:
	-	in: %appDir%/Domain/*Repository
```
