### ISSUE TITLE
Improving error message when Reader not found

### ISSUE THREAD

**Issue by freiondrej** [contributte/doctrine-orm#86]
I fought with exception `Missing Reader service` from `\Nettrine\ORM\DI\OrmAnnotationsExtension::loadConfiguration()` - I discovered that the order in which the extensions are registered matters and that it makes sense to register Nettrine\Annotations\DI\AnnotationsExtension before Nettrine\ORM extensions. Maybe the exception message could advise that?

**Comment by f3l1x** [comment]
Sure, good idea.
