### ISSUE TITLE
Impossible to set own second level cache

### ISSUE THREAD

**Issue by paveltizek** [contributte/doctrine-orm#94]
Cannot set own  cache configuration factory as service like this:

`nettrine.orm.cache:`
   `     secondLevelCache: @redisCacheConfigurationFactory::create(%tempDir%)`

`services:`
    `redisCacheConfigurationFactory: Eshop\Core\Cache\RedisCacheConfigurationFactory(%redis.host%, %redis.port%)`

I have to create next service so working result is 

`services:
    redisCacheConfigurationFactory: Eshop\Core\Cache\RedisCacheConfigurationFactory(%redis.host%, %redis.port%)
    redisCacheConfiguration: @redisCacheConfigurationFactory::create(%tempDir%)`

`nettrine.orm.cache:
    secondLevelCache: @redisCacheConfiguration`

**Comment by f3l1x** [comment]
Yep, that's seems correct.

**Comment by f3l1x** [comment]
It's now in master, it will be possible in 0.10.
