### ISSUE TITLE
Using EntityManagerDecorator instead of EntityManager seems to be quite "experimental"

### ISSUE THREAD

**Issue by thorewi** [contributte/doctrine-orm#98]
Hello,

I know that using EntityManagerDecorator is recommended by Doctrine authors, but according to this issue https://github.com/doctrine/orm/issues/5820 and my own experience, it's not ready to be heavily used yet. 

Does someone use it successfully on large projects?

Thank you.

**Comment by f3l1x** [comment]
Is it OK?

**Comment by thorewi** [comment]
I guess the issues mentioned here https://github.com/doctrine/orm/issues/5820 are still valid, but this code:

```php

use Doctrine\ORM\EntityManagerInterface;
use Nettrine\ORM\EntityManagerDecorator;

class EntityManager extends EntityManagerDecorator
{
	protected \Doctrine\ORM\Configuration $config;

	public function __construct(EntityManagerInterface $wrapped, \Doctrine\ORM\Configuration $config)
	{
		$this->config = $config;
		parent::__construct($wrapped);
	}

	public function getRepository($entityName)
	{
		return $this->config->getRepositoryFactory()->getRepository($this, $entityName);
	}

}
```

seems to work for our needs. I guess we can't do anything about it anyway. I was just curious about others solutions.
