### ISSUE TITLE
Docs: clarify consequence of using `autoGenerateProxyClasses` with `%debugMode%`

### ISSUE THREAD

**Issue by dakur** [contributte/doctrine-orm#99]
In docs, there is a statement:

![image](https://user-images.githubusercontent.com/9862581/170508188-5df02e7f-7e66-43fc-9901-a09529c2417a.png)

But there is no mention about that `orm:generate-proxies` has to be run on production otherwise the application will fail.

Mine fail when fixtures were applying.

**Comment by dakur** [comment]
Yes, as a point of reference yes. But the problem with `%debugMode%` must be explained in-place. Something like:

> Note that in case of `autoGenerateProxyClasses` is resolved to `false` (in production mode), proxy entities have to be generated manually with CLI command. Refer to [doctrine docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/advanced-configuration.html#auto-generating-proxy-classes-optional) for more information.

**Comment by f3l1x** [comment]
Resolved.
